title: Jizhou Wang
blank_title: true
logo: /assets/img/Jawing.gif
email: jizhou.wang@mila.quebec
description: Avid coder in AI 🤖 Rhythmic Paws 🎹 Maximize Positive Entropy 💞
show_downloads: false
google_analytics: G-S3Y9V0TSFC
favicon: true
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
